#!/usr/bin/env bash
# A script that transfers a file over ssh
# to another server

filePath=${1}
ipAdrr=${2}
name=${3}
sshPath=${4}

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "${sshPath}" "${filePath}" "${name}"@"${ipAdrr}":~/
fi
