#!/usr/bin/env bash


numParameters=$#
filePath=$1
ip=$2
user=$3
sshPath=$4

if [[ "$numParameters" -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o "StrictHostKeyChecking=no" -i "$sshPath" "$filePath" "$user"@"$ip":~/
fi
