#!/usr/bin/env bash
# A script that installs Nginx and congigures it

# Installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo apt install ufw
sudo ufw allow ssh
sudo ufw enable

# Configuring listening on port 80
sudo ufw allow 'Nginx HTTP'

# Default message configuration
echo 'Hello World!' | sudo tee /var/www/html/index.html

#Restarting
sudo service nginx restart
