#!/usr/bin/env bash
# A script that installs Nginx and congigures it

# Installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configuring listening on port 80
sudo ufw allow 'Nginx HTTP'

# Default message configuration
echo 'Hello World!' | sudo tee /var/www/html/index.html

#Restarting
sudo service nginx restart

# Redirecting -- I used the escape character because '/' is a delimiter for sed command
redir="server_name _;\n\trewrite ^/redirect_me https:\/\/github.com\/BunmiFash permanent"
sudo sed -i "s/server_name _;/${redir}/" /etc/nginx/sites-available/default;
