#!/usr/bin/env bash
# A script that installs HAProxy and configures it with the roundrobin algorithm

# Installing HAProxy
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

# Enabling and testing HAProxy for init script
echo ENABLED=1 | sudo tee /etc/default/haproxy
service haproxy

# Configuring HAProxy
sudo mv /etc/haproxy/haproxy.cfg{,.original} #So that I can create my own config file
sudo cp /etc/haproxy/haproxy.cfg.original /etc/haproxy/haproxy.cfg

frontend="frontend bunmi-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend bunmi-backend"
backend="backend bunmi-backend\n\tbalance roundrobin\n\tserver 155152-web-01 54.173.89.51:80 check\n\tserver 155152-web-02	54.85.26.50:80 check"

echo -e  "${frontend}" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "${backend}" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
