#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

counter=0
while [[ ${counter} -ne 100 ]]
do
	counter=$((counter+1))
	if ((counter % 15 == 0)); then
		echo "FizzBuzz"
	elif ((counter % 5 == 0)); then
		echo "Buzz"
	elif ((counter % 3)); then
		echo "Fizz"
	else
		echo ${counter}
	fi
done
