#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=-1
while [[ ${hour} -ne 12 ]]; do
	hour=$((hour+1))
	echo "Hour: ${hour}"
	minute=0
	while [[ ${minute} -ne 59 ]]; do
		minute=$((minute+1))
		echo ${minute}
	done
done
