#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.another
echo "127.0.0.2		localhost" > ~/hosts.another
echo "8.8.8.8		facebook.com" >> ~/hosts.another
cp -f ~/hosts.another /etc/hosts
